In [1]:
!pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (4.3.0)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cryptography>=44.0.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (46.0.4)
Requirement already satisfied: pyOpenSSL<26.0.0,>=24.0.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (25.3.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (2.11.0)
Requirement already satisfied: pytz in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (2.32.5)
Requirement already satisfied: packaging in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (3.4.3)
Requirement already satisfied: idna<4,>=3.7 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (3.10)
Requirement already satisfied: certifi>=2024.7.4 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (2025.10.5)
Requirement already satisfied: typing_extensions<5,>=4.3 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (3.23.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (4.5.0)
Requirement already satisfied: tomlkit in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (0.14.0)
Requirement already satisfied: boto3>=1.24 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (1.42.57)
Requirement already satisfied: botocore>=1.24 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from snowflake-connector-python) (1.42.57)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from boto3>=1.24->snowflake-connector-python) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from botocore>=1.24->snowflake-connector-python) (2.5.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=44.0.1->snowflake-connector-python) (2.0.0)
Requirement already satisfied: pycparser in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from cffi>=2.0.0->cryptography>=44.0.1->snowflake-connector-python) (2.23)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python) (1.17.0)

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import snowflake.connector

In [3]:
import snowflake.connector

conn = snowflake.connector.connect(
    user="BARATH2415",
    password="Barath24151515",
    account="qfjjsva-ql35240",  # ← FIXED
    warehouse="ANALYST_WH",
    database="HYUNDAI",
    schema="PUBLIC"
)
print("Connected successfully!")

Connected successfully!

In [4]:
print(type(conn))

<class 'snowflake.connector.connection.SnowflakeConnection'>

In [5]:
query1="SELECT * FROM SERVICE"
query2="SELECT * FROM VEHICLE"
query3="SELECT * FROM SALES"
query4="SELECT * FROM CUSTOMERS"

In [6]:
import pandas as pd

df_customers =pd.read_sql(query4,conn)
df_vehicles = pd.read_sql(query2,conn)
df_sales = pd.read_sql(query3,conn)
df_service =pd.read_sql(query1,conn)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9496\230456503.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_customers =pd.read_sql(query4,conn)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9496\230456503.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_vehicles = pd.read_sql(query2,conn)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9496\230456503.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_sales = pd.read_sql(query3,conn)
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_9496\230456503.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_service =pd.read_sql(query1,conn)

In [7]:
df_customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CUSTOMER_ID   5000 non-null   int64
 1   NAME          5000 non-null   object
 2   AGE           5000 non-null   int64
 3   GENDER        5000 non-null   object
 4   CITY          5000 non-null   object
 5   INCOME        5000 non-null   int64
 6   CREDIT_SCORE  5000 non-null   int64
dtypes: int64(4), object(3)
memory usage: 273.6+ KB

In [78]:
df_vehicles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   VEHICLE_ID     2000 non-null   int64
 1   MODEL_NAME     2000 non-null   object
 2   ENGINE_TYPE    2000 non-null   object
 3   BASE_PRICE     2000 non-null   int64
 4   SEGMENT        2000 non-null   object
 5   PURCHASE_YEAR  2000 non-null   int64
dtypes: int64(3), object(3)
memory usage: 93.9+ KB

In [8]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SALE_ID        10000 non-null  int64
 1   CUSTOMER_ID    10000 non-null  int64
 2   VEHICLE_ID     10000 non-null  int64
 3   SALE_DATE      10000 non-null  object
 4   FINAL_PRICE    10000 non-null  int64
 5   DISCOUNT       10000 non-null  int64
 6   DEALER_REGION  10000 non-null  object
 7   PAYMENT_TYPE   10000 non-null  object
dtypes: int64(5), object(3)
memory usage: 625.1+ KB

In [7]:
df_service.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_id      50000 non-null  int64
 1   vehicle_id      50000 non-null  int64
 2   service_date    50000 non-null  object
 3   service_type    50000 non-null  object
 4   service_cost    50000 non-null  int64
 5   warranty_claim  50000 non-null  object
 6   dealer_region   50000 non-null  object
dtypes: int64(3), object(4)
memory usage: 2.7+ MB

In [9]:
df_customers.isnull().sum()

CUSTOMER_ID     0
NAME            0
AGE             0
GENDER          0
CITY            0
INCOME          0
CREDIT_SCORE    0
dtype: int64

In [81]:
df_vehicles.isnull().sum()

VEHICLE_ID       0
MODEL_NAME       0
ENGINE_TYPE      0
BASE_PRICE       0
SEGMENT          0
PURCHASE_YEAR    0
dtype: int64

In [11]:
df_sales.isnull().sum()

sale_id          0
customer_id      0
vehicle_id       0
sale_date        0
final_price      0
discount         0
dealer_region    0
payment_type     0
dtype: int64

In [82]:
df_service.isnull().sum()

SERVICE_ID        0
VEHICLE_ID        0
SERVICE_DATE      0
SERVICE_TYPE      0
SERVICE_COST      0
WARRANTY_CLAIM    0
DEALER_REGION     0
dtype: int64

In [10]:
df_service = df_service.drop_duplicates(subset=['SERVICE_ID'])
df_vehicles = df_vehicles.drop_duplicates(subset=['VEHICLE_ID'])

In [11]:
df_service['SERVICE_DATE'] = pd.to_datetime(df_service['SERVICE_DATE'])
df_vehicles['PURCHASE_YEAR'] = df_vehicles['PURCHASE_YEAR'].astype(int)
df_service['SERVICE_COST'] = df_service['SERVICE_COST'].astype(float)

In [12]:
df_service.dtypes

SERVICE_ID                 int64
VEHICLE_ID                 int64
SERVICE_DATE      datetime64[ns]
SERVICE_TYPE              object
SERVICE_COST             float64
WARRANTY_CLAIM              bool
DEALER_REGION             object
dtype: object

In [13]:
df_service['service_type'] = df_service['service_type'].str.strip().str.title()
df_service['warranty_claim'] = df_service['warranty_claim'].str.strip().str.title()
df_vehicles['engine_type'] = df_vehicles['engine_type'].str.strip().str.title()

KeyError: 'service_type'

In [14]:
df_ml = df_service.merge(df_vehicles,on='VEHICLE_ID',how='left')

In [15]:
df_ml.shape

(50000, 12)

In [17]:
current_year = 2026
df_ml['VEHICLE_AGE'] = current_year - df_ml['PURCHASE_YEAR']

In [18]:
df_ml.head(10)

,SERVICE_ID,VEHICLE_ID,SERVICE_DATE,SERVICE_TYPE,SERVICE_COST,WARRANTY_CLAIM,DEALER_REGION,MODEL_NAME,ENGINE_TYPE,BASE_PRICE,SEGMENT,PURCHASE_YEAR,VEHICLE_AGE
0,1,1750,2024-02-23,Minor,10013.0,True,Hyderabad,Alcazar,Diesel,1476542,SUV,2020,6
1,2,1168,2025-11-15,Repair,10014.0,True,Bangalore,Alcazar,Petrol,1652906,SUV,2025,1
2,3,1478,2025-05-29,Minor,6827.0,True,Delhi,Elantra,Petrol,919420,Sedan,2022,4
3,4,1232,2025-11-16,Repair,10340.0,False,Mumbai,Elantra,Petrol,1034116,Sedan,2022,4
4,5,1530,2025-06-13,Minor,9396.0,False,Chennai,Elantra,Diesel,1031850,Sedan,2018,8
5,6,978,2024-05-10,Repair,11879.0,False,Mumbai,Tucson,Petrol,2395718,SUV,2023,3
6,7,723,2024-12-15,Minor,11347.0,False,Delhi,Venue,Petrol,1710464,SUV,2018,8
7,8,1734,2025-09-27,Repair,15131.0,True,Chennai,Creta,Diesel,2429564,SUV,2016,10
8,9,1319,2026-02-17,Repair,13619.0,True,Mumbai,Ioniq,Electric,3708338,Electric,2015,11
9,10,687,2024-09-21,Repair,11266.0,False,Hyderabad,Creta,Diesel,1601365,SUV,2024,2

In [19]:
df_ml['WARRANTY_FLAG'] = df_ml['WARRANTY_CLAIM'].map({True: 1,False: 0})

In [20]:
df_ml.head()

,SERVICE_ID,VEHICLE_ID,SERVICE_DATE,SERVICE_TYPE,SERVICE_COST,WARRANTY_CLAIM,DEALER_REGION,MODEL_NAME,ENGINE_TYPE,BASE_PRICE,SEGMENT,PURCHASE_YEAR,VEHICLE_AGE,WARRANTY_FLAG
0,1,1750,2024-02-23,Minor,10013.0,True,Hyderabad,Alcazar,Diesel,1476542,SUV,2020,6,1
1,2,1168,2025-11-15,Repair,10014.0,True,Bangalore,Alcazar,Petrol,1652906,SUV,2025,1,1
2,3,1478,2025-05-29,Minor,6827.0,True,Delhi,Elantra,Petrol,919420,Sedan,2022,4,1
3,4,1232,2025-11-16,Repair,10340.0,False,Mumbai,Elantra,Petrol,1034116,Sedan,2022,4,0
4,5,1530,2025-06-13,Minor,9396.0,False,Chennai,Elantra,Diesel,1031850,Sedan,2018,8,0

In [93]:
df_ml.shape

(50000, 14)

In [94]:
y=df_ml["SERVICE_COST"]

In [145]:
X = df_ml[[
    
        'VEHICLE_AGE','WARRANTY_FLAG','BASE_PRICE','SERVICE_TYPE','ENGINE_TYPE','SEGMENT','DEALER_REGION']]

In [146]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [147]:
numeric_features = ['VEHICLE_ID','WARRANTY_FLAG', 'BASE_PRICE']

categorical_features = [ 'SERVICE_TYPE', 'ENGINE_TYPE', 'SEGMENT', 'DEALER_REGION']

In [148]:
preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ],
    remainder='passthrough'
)

In [149]:
X_processed = preprocessor.fit_transform(X)

In [150]:
print(X_processed.shape)

(50000, 18)

In [151]:
X_processed

array([[0.000000e+00, 1.000000e+00, 0.000000e+00, ..., 6.000000e+00,
        1.000000e+00, 1.476542e+06],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, ..., 1.000000e+00,
        1.000000e+00, 1.652906e+06],
       [0.000000e+00, 1.000000e+00, 0.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 9.194200e+05],
       ...,
       [1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 2.000000e+00,
        1.000000e+00, 7.833110e+05],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, ..., 0.000000e+00,
        1.000000e+00, 4.671910e+06],
       [1.000000e+00, 0.000000e+00, 0.000000e+00, ..., 4.000000e+00,
        1.000000e+00, 9.068570e+05]], shape=(50000, 18))

In [130]:
type(X_processed)

numpy.ndarray

In [152]:
from sklearn.model_selection import train_test_split

In [153]:
x_train,x_test,y_train,y_test=train_test_split(X_processed,y,test_size=0.2,random_state=42)

In [154]:
x_train.shape

(40000, 18)

In [109]:
y_train.shape

(40000,)

In [155]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100,random_state=42,max_depth=10)
model.fit(x_train,y_train)

RandomForestRegressor(max_depth=10, random_state=42)

In [156]:
y_pred=model.predict(x_test)
print(y_pred[:5])

[13947.17830068 15973.18810883  7559.39609869 19030.22578691
 12534.48898498]

In [157]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [158]:
mae=mean_absolute_error(y_test,y_pred)
rmse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)

In [159]:
print("mae:",mae)
print("rmse:",rmse)
print("r2:",r2)

mae: 252.08213191981753
rmse: 85522.84089213355
r2: 0.9931401676997444

In [115]:
pip install joblib

Requirement already satisfied: joblib in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (1.5.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [160]:
import joblib as jb
jb.dump(model,"servicecostmodel.pkl")

['servicecostmodel.pkl']

In [161]:
jb.dump(preprocessor,"preprocessor.pkl")

['preprocessor.pkl']